apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-cluster-application-set
  namespace: argocd
spec:
  generators:
  - clusters: {} # Automatically use all clusters defined within Argo CD
  template:      
    metadata:
      name: '{{name}}-billing-app'
    spec:
      # The project the application belongs to.
      project: default

      # Source of the application manifests
      source:
        repoURL: https://github.com/eambrosino/gitops-cert-level-2-examples.git
        targetRevision: HEAD
        path: ./application-sets/manifests
      
      # Destination cluster and namespace to deploy the application
      destination:
        server: '{{server}}'
        namespace: billing

      # Sync policy
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated:
          prune: true
          selfHeal: true
